FROM achernetzov/wine

RUN sudo wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
&& sudo chmod +x winetricks \
&& sudo mv ./winetricks /usr/local/bin/winetricks

#RUN winetricks vcrun2015

# for winetricks gui
#RUN apt-get install -y zenity && cabextract


