FROM achernetzov/wine

RUN wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
&& chmod +x winetricks \
&& mv ./winetricks /usr/local/bin/winetricks

#RUN winetricks vcrun2015


